### ISSUE TITLE
[FEATURE] [MC] Add tipped arrows or other random consumables to Potshot

### ISSUE THREAD

**Issue by ookiegajwa** [LEATplex/LEATplex#7]
_This is a development tracking issue for `LEATplex v1.11`. It will be closed when development on this feature is done, **not** when it is added to the public server. The feature will be added when development on `LEATplex v1.11` is complete._

Development on `LEATplex v1.11` can be followed at [LEATplex v1.11 - Potshot Update](https://github.com/orgs/LEATplex/projects/3)

Add (optional) random tipped arrow spawns or other consumables to Potshot.

**Comment by ookiegajwa** [comment]
Current possible ideas:
* firework crossbow
* explosive arrow
* incendiary arrow
* smoke cloud
* blindness arrow
* poison arrow
* slowness arrow
* single-use elytra
* levitation aoe
* deployable cover

Note that these are **ideas** and as such may not be included in the final release. Feel free to suggest your own below!

@Timberwolf857

**Comment by Timberwolf857** [comment]
More ideas:
Cobweb arrow(temporary, for chokepoints
Grappling arrow(maybe an arrow that leaves a temp. warped vine trail behind it?)
Invisibility potion(self explanatory)
Assassin's dagger(one durability instakill iron sword)
Crystal Matrix(throwable that becomes an end crystal 3s after landing)

**Comment by ookiegajwa** [comment]
Thanks for the suggestions! Crystal Matrix made it in, as well as versions of most of the other things. More may always be added in the future :)
